
spring:
  profiles:
    active: ${SPRING_PROFILE}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
  flyway:
    enabled: true
    validate-on-migrate: true
